### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by NotTheImpasta**
not done yet

### CODE REVIEW

**Comment by NotTheImpasta** [comment]
note that french autocorrect might mess things up

**Comment by NotTheImpasta** [comment]
i think i did enough

here's the link although i only really changed cursor selecting
https://nottheimpasta.github.io/MCDiamondFire-Awesome/

**Comment by SquaredStudios-MC** [comment]
@UserUNP @CheaterTim ‼️

**Comment by SquaredStudios-MC** [comment]
> After you're done click "squash and merge"

i know

**Comment by UserUNP** [comment]
@NotTheImpasta also change the data.json to explicitly include the fontawesome icon name so there's no if statements in the Properties component

**Comment by SquaredStudios-MC** [comment]
> @... also change the data.json to explicitly include the fontawesome icon name so there's no if statements in the Properties component

i'll do that instead

**Comment by UserUNP** [comment]
i did say to squash and merge you nincompoop

**Pull request merged**
