### PR TITLE
fix table of contents and rename "isMobileDevice" to "isMd"

### PR DESCRIPTION
**Pull request by CheaterTim**

### CODE REVIEW

**Comment by CheaterTim** [comment]
`md` is referring to the tailwind rule `md:` (next to `sm` and `lg`), and quite literally does the opposite of checking if the screen is a mobile device, it checks if the screen is *bigger* than `md`, thus if it *is md*

**Comment by NotTheImpasta** [comment]
for real

**Comment by NotTheImpasta** [comment]
where's the merge button

**Comment by AstroSquared** [comment]
> where's the merge button

In your walls

**Pull request merged**
