### PR TITLE
remake

### PR DESCRIPTION
**Pull request by CheaterTim**
live version of this pr is at https://cheatertim.github.io/MCDiamondFire-Awesome/

### CODE REVIEW

**Comment by CheaterTim** [comment]
merge right now

**Comment by SquaredStudios-MC** [comment]
Oven don't merge yet I'll look when I get home

**Comment by SquaredStudios-MC** [comment]
I cannot review on mobile but please make Version and Deprecated labels green

**Comment by NotTheImpasta** [comment]
Warning: this is a review containing an opinion on the internet. Be careful!

# Good work!

* Scrollbar looks amazing
* I love the accent color (green)
* The icons in the header looks cool
* Overall amazing website
* The "outdated" gradient looks cool

# My issues with the site

* The links are green for the "Docs", "NPM", "Discord", whatever, but the text next to "Version" and "Deprecated" are not green, and that's inconsistent
* The bulletpoints at the "Table of contents" have the same issue: the bullets are green (should be white)
* The black background looks good, but it could be improved. A faded gradient or a faded image would look cool
* The "Version" icon does not seam appropriate, and same for "Deprecated"

**Comment by SquaredStudios-MC** [comment]
A gradient like that is exactly what I meant.

Skull could maybe be a tombstone? If not it's fine I don't care that much.

After looking on desktop I see what you mean with the non green text.

And the white bullets on the table of contents looks better

**Comment by CheaterTim** [comment]
> Skull could maybe be a tombstone? If not it's fine I don't care that much.

the tombstone icon is only available in fontawesome pro.

**Comment by CheaterTim** [comment]
> Issue I found (to reproduce scroll up/down too much on phone)

I'm pretty sure this is a problem with your browser, the site does nothing related to scrolling except for setting `scroll-behavior` to `smooth`

**Comment by SquaredStudios-MC** [comment]
Fixes #3

**Pull request merged**
